### ISSUE TITLE
Output folder on Github Actions needs to be unique per build

### ISSUE THREAD

**Issue by tyhoff** [memfault/conda-recipes#15]
I believe we are using the same build output folder on all builds, and they are stacking. When we build Python 3.7/8/9/10, they are all about 30-40MB and each package seems to grow. 

<img width="986" alt="image" src="https://user-images.githubusercontent.com/1041679/174294678-99574b76-854a-4e07-9fb2-818b8bb6a923.png">

**Comment by tyhoff** [comment]
Looking at the action, `conda build --output PACKAGE_DIR PACKAGE_DIR will output the .gz to the package (which is the recipe) directory, but Conda by default includes the recipe directory in the <package>/info/ directory. 

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/1041679/174296001-e29995f1-4824-44e2-98a3-5d7f80ee0dd7.png">

**Comment by noahp** [comment]
Oof 🤦 what a pain. Ok, I'll fix it
