### ISSUE TITLE
Any chance of supporting a Windows build of the cpputest conda package?

### ISSUE THREAD

**Issue by barbibulle** [memfault/conda-recipes#2]
Conda doesn't seem to support opting out of selected dependencies on some platforms only, so depending on `cpputest` breaks on Windows platforms. If producing a binary isn't easy, maybe the next best would be to have a dummy for Windows, so that cross-platform environments that depend on `cpputest` for Linux and macOS wouldn't break when installed on Windows?

**Comment by topher200** [comment]
Our development team is on MacOS and Linux, we have no plans to support Windows with these packages. Sorry and good luck!
